### ISSUE TITLE
Merge with https://www.gatsbyjs.org/packages/gatsby-plugin-gdpr-cookies/

### ISSUE THREAD

**Issue by SimonKlausLudwig** [andreas-straub/gatsby-plugin-gdpr-tracking#1]
These two plugins almost do the same (Thanks for the great plugin). I do miss facebook in your plugin and i miss gtag at his plugin. Wouldnt it make sense to 'merge' both projects ?

**Comment by andreas-straub** [comment]
> These two plugins almost do the same (Thanks for the great plugin). I do miss facebook in your plugin and i miss gtag at his plugin. Wouldnt it make sense to 'merge' both projects ?

@SimonKlausLudwig Hi Simon, yes i was also thinking about adding the Facebook Pixel to this plugin. But I haven't needed it yet. Would you make a PR? I mean it's almost copy paste

**Comment by andreas-straub** [comment]
Added FB tracking :-)
