### ISSUE TITLE
Expose options to set cookie flags for gtag 

### ISSUE THREAD

**Issue by mhatvan** [andreas-straub/gatsby-plugin-gdpr-tracking#2]
Firefox is throwing `Some cookies are misusing the recommended “sameSite“ attribute`

I get this message 4 times, with further details for each cookie, for example:
`Cookie “_ga” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies`

As can be read in the article here: https://www.simoahava.com/analytics/cookieflags-field-google-analytics/, it would be great to be able to pass at least:  `cookie_flags: 'secure;samesite=none'` to the plugin, or you make it the default and overwritable to avoid having cookies rejected in future browser versions.

**Comment by andreas-straub** [comment]
@mhatvan Thanks for a hint! This is a good idea. I'm going to implement this feature.

**Comment by andreas-straub** [comment]
Implemented in v1.1.0
