### ISSUE TITLE
Getting multiple GA instances running

### ISSUE THREAD

**Issue by hoffination** [andreas-straub/gatsby-plugin-gdpr-tracking#5]
In my testing of the GA instance, I'm getting multiple GA instances resulting on the final page and in the GA console. You can see that on this deploy of the site (https://5f28bdade4b141000740feb5--nifty-lamport-5ca10b.netlify.app/).

Not sure what could be causing it. Moved the plugin around to see if anything was interfering. Same result as the first or last plugin.

Here's my plugin config:
```
{
      resolve: `gatsby-plugin-gdpr-tracking`,
      debug: false,
      options: {
        googleAnalytics: {
          // The property ID; the tracking code won't be generated without it.
          trackingId: "UA-SOME_ID",
          // Defines it google analytics should be started with out the cookie consent
          autoStart: false, // <--- default
          // Setting this parameter is optional
          anonymize: false, // <--- default
          // Name of the cookie, that enables the tracking if it is true
          controlCookieName: "gdpr-analytics-enabled", // <--- default
          cookieFlags: "secure;samesite=none", // <--- default
        },
        googleAds: {
          // The property ID; the tracking code won't be generated without it.
          trackingId: "",
          // Setting this parameter is optional
          anonymize: false, // <--- default
          // Name of the cookie, that enables the tracking if it is true
          controlCookieName: "gdpr-marketing-enabled", // <--- default
          cookieFlags: "secure;samesite=none", // <--- default
        },
        hotjar: {
          // The Hotjar ID; the tracking code won't be generated without it.
          trackingId: "",
          // Your Hotjar snippet version
          snippetVersion: "6", // <--- default
          // Name of the cookie, that enables the tracking if it is true
          controlCookieName: "gdpr-analytics-enabled", // <--- default
        },
        // defines the environments where the tracking should be available  - default is ["production"]
        environments: ["production", "development"],
      },
    },
```

**Gatsby Config**

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.0/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 75.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.18.17 => 2.18.17 
    gatsby-image: ^2.2.37 => 2.2.37 
    gatsby-plugin-catch-links: ^2.1.21 => 2.1.21 
    gatsby-plugin-feed: ^2.3.25 => 2.3.25 
    gatsby-plugin-gdpr-tracking: ^1.1.1 => 1.1.1 
    gatsby-plugin-manifest: ^2.2.34 => 2.2.34 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.18 => 3.1.18 
    gatsby-plugin-sharp: ^2.3.10 => 2.3.10 
    gatsby-plugin-sitemap: ^2.2.24 => 2.2.24 
    gatsby-plugin-typography: ^2.3.20 => 2.3.20 
    gatsby-remark-copy-linked-files: ^2.1.33 => 2.1.33 
    gatsby-remark-images: ^3.1.39 => 3.1.39 
    gatsby-remark-prismjs: ^3.3.28 => 3.3.28 
    gatsby-remark-responsive-iframe: ^2.2.30 => 2.2.30 
    gatsby-remark-smartypants: ^2.1.19 => 2.1.19 
    gatsby-source-filesystem: ^2.1.43 => 2.1.43 
    gatsby-transformer-remark: ^2.6.45 => 2.6.45 
    gatsby-transformer-sharp: ^2.3.9 => 2.3.9

**Comment by hoffination** [comment]
Updating my dependencies resolved the problem! 😄 


  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.0/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 75.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.20.0 => 2.24.27 
    gatsby-image: ^2.4.14 => 2.4.14 
    gatsby-plugin-catch-links: ^2.3.11 => 2.3.11 
    gatsby-plugin-feed: ^2.5.11 => 2.5.11 
    gatsby-plugin-gdpr-tracking: ^1.1.1 => 1.1.1 
    gatsby-plugin-manifest: ^2.4.21 => 2.4.21 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sharp: ^2.6.24 => 2.6.24 
    gatsby-plugin-sitemap: ^2.4.11 => 2.4.11 
    gatsby-plugin-typography: ^2.5.10 => 2.5.10 
    gatsby-remark-copy-linked-files: ^2.3.12 => 2.3.12 
    gatsby-remark-images: ^3.3.24 => 3.3.24 
    gatsby-remark-prismjs: ^3.5.10 => 3.5.10 
    gatsby-remark-responsive-iframe: ^2.4.12 => 2.4.12 
    gatsby-remark-smartypants: ^2.3.10 => 2.3.10 
    gatsby-source-filesystem: ^2.3.23 => 2.3.23 
    gatsby-transformer-remark: ^2.8.27 => 2.8.27 
    gatsby-transformer-sharp: ^2.5.12 => 2.5.12

**Comment by andreas-straub** [comment]
Great! Thank you for the info.

Ben Hofferber <notifications@github.com> schrieb am Di. 4. Aug. 2020 um
21:16:
